#!/bin/bash
#SBATCH --job-name=test.1DMRG.tensor.mea
#SBATCH --partition=TH-WS,TH-CL
#SBATCH --nodes=1
#SBATCH --tasks-per-node=1
#SBATCH --cpus-per-task=10
#SBATCH --mem-per-cpu=3Gb
#SBATCH --threads-per-core=1
#SBATCH --begin=now
#SBATCH --time=240:00:00
#SBATCH --mail-user=chiamin.chung@lmu.de
#SBATCH --no-requeue
#SBATCH --constraint=

scratch=/data/ChiaMin.Chung/$SLURM_JOB_ID

slurm_startjob()
{
    # Define variables

    # Go to scratch
    mkdir -p $scratch
    #if [ -n "$input" ]; then
        cp $input $scratch
    #fi
    cd $scratch

    # Pre process
    #if [ -n "$output" ]; then
        cat $0 >> $SLURM_SUBMIT_DIR/$output
        slurm_info_out >> $SLURM_SUBMIT_DIR/$output
    #fi

    # Execution

    # After finish
    echo Job Done
}

slurm_info_out()
{
    echo "----- Job Information -----"
    date
    echo
    echo "The job will be started on the following node(s):"
    echo $SLURM_JOB_NODELIST
    echo
    echo "Slurm User:         $SLURM_JOB_USER"
    echo "Run Directory:      $SLURM_JOB_NODELIST:$(pwd)"
    echo "Job ID:             $SLURM_JOB_ID"
    echo "Submitted From:     $SLURM_SUBMIT_HOST:$SLURM_SUBMIT_DIR"
    echo "---------------------------"
    echo
}

slurm_info_out
slurm_startjob
