#!/bin/bash
#SBATCH --job-name=test.1DMRG.tensor.mea
#SBATCH --partition=TH-CL
#SBATCH --nodes=1
#SBATCH --tasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=1Gb
#SBATCH --threads-per-core=1
#SBATCH --begin=now
#SBATCH --time=48:00:00
#SBATCH --mail-user=chiamin.chung@lmu.de
#SBATCH --no-requeue

echo gg
